using Gaugefields
using JACC
using LatticeDiracOperators
using LatticeMatrices
using Test

JACC.@init_backend
include(joinpath(@__DIR__, "test_communicator.jl"))

@testset "Grid Shamir domain-wall PP and J5q reference" begin
    # Independent reference: Grid commit
    # 0ac72cb6a30ccdc41d664e7e0759f0c8833078f1, generated by
    # test/references/grid/qcdm_domainwall_mres_reference.cc.
    grid_PP = ComplexF64[
        0.14592222922302317 + 5.4286636189814794e-20im,
        0.097088345874940141 + 2.041030642822601e-20im,
        0.059072177389470064 + 6.7600199723056984e-21im,
        0.097088345874940141 + 1.0307496632516971e-21im,
    ]
    grid_J5qP = ComplexF64[
        0.049655759640000491 + 1.6361798280871522e-21im,
        0.0028730807215859382 + 1.9668614644521858e-22im,
        0.00020791404200740403 + 4.3292054124976462e-23im,
        0.0028730807215859378 + 1.1579717795075363e-21im,
    ]

    number_of_processes = ldo_test_comm_size()
    lattice_size = (4, 4, 4, 4)
    lattice_size[1] % number_of_processes == 0 || error(
        "this reference test needs a process count dividing NX=4")
    process_grid = (number_of_processes, 1, 1, 1)
    U = Initialize_Gaugefields(
        3, 1, lattice_size...;
        condition="cold",
        isMPILattice=true,
        PEs=process_grid,
        verbose_level=0,
    )
    theta = 1.1
    LatticeMatrices.set_global_component!(
        U[1].U, cis(theta), 1, 1, (1, 1, 1, 1))
    LatticeMatrices.set_global_component!(
        U[1].U, cis(-theta), 2, 2, (1, 1, 1, 1))
    Gaugefields.set_wing_U!(U[1])

    L5 = 4
    field5 = Initialize_pseudofermion_fields(U[1], "Domainwall"; L5)
    parameters = Dict{String,Any}(
        "Dirac_operator" => "Domainwall",
        "mass" => 0.1,
        "L5" => L5,
        # Grid's M5=1 corresponds to the existing LM/LDO M=-1 convention.
        "M" => -1.0,
        # Grid specifies a residual norm; LDO compares the squared residual.
        "eps_CG" => 1e-28,
        "MaxCGstep" => 100_000,
        "method_CG" => "bicg",
        "verbose_level" => 0,
        "boundarycondition" => [1, 1, 1, -1],
    )
    D = Dirac_operator(U, field5, parameters)
    propagators = domainwall_physical_point_propagators(
        D, field5; source_position=(1, 1, 1, 1))
    correlators = domainwall_residual_mass_correlator(
        propagators.five_dimensional; origin=(1, 1, 1, 1))

    @test all(diagnostic ->
        diagnostic.recursive_residual_squared <= diagnostic.target_residual_squared,
        propagators.diagnostics)
    @test correlators.PP ≈ grid_PP rtol=2e-11 atol=2e-13
    @test correlators.J5qP ≈ grid_J5qP rtol=2e-11 atol=2e-13
    @test correlators.ratio ≈ grid_J5qP ./ grid_PP rtol=3e-11 atol=3e-13
end
